spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: testUser
    password: testPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate #update  #create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true